#ifndef COOGLEIOT_CONFIG_H
#define COOGLEIOT_CONFIG_H

//#define COOGLEIOT_DEBUG

constexpr auto COOGLEIOT_VERSION = "1.3.1";

#ifndef COOGLEIOT_SPIFFS_LOGFILE
#define COOGLEIOT_SPIFFS_LOGFILE "/coogleiot-log.txt"
#endif

#ifndef COOGLEIOT_LOGFILE_MAXSIZE
#define COOGLEIOT_LOGFILE_MAXSIZE 32768 // 32k
#endif

#ifndef COOGLEIOT_STATUS_INIT
#define COOGLEIOT_STATUS_INIT 500
#endif

#ifndef COOGLEIOT_STATUS_WIFI_INIT
#define COOGLEIOT_STATUS_WIFI_INIT 250
#endif

#ifndef COOGLEIOT_STATUS_MQTT_INIT
#define COOGLEIOT_STATUS_MQTT_INIT 100
#endif

#define COOGLEIOT_MAGIC_BYTES "ciot"

#ifndef COOGLEIOT_AP
#define COOGLEIOT_AP "COOGLEIOT_"
#endif

#ifndef COOGLEIOT_AP_DEFAULT_PASSWORD
#define COOGLEIOT_AP_DEFAULT_PASSWORD "coogleiot"
#endif

#ifndef COOGLEIOT_DEFAULT_MQTT_CLIENT_ID
#define COOGLEIOT_DEFAULT_MQTT_CLIENT_ID "coogleIoT"
#endif

#ifndef COOGLEIOT_DEFAULT_MQTT_PORT
#define COOGLEIOT_DEFAULT_MQTT_PORT 1883
#endif

#ifndef COOGLEIOT_DEFAULT_MQTT_QOS
#define COOGLEIOT_DEFAULT_MQTT_QOS 1
#endif

#ifndef COOGLEIOT_DEFAULT_MQTT_RETAIN
#define COOGLEIOT_DEFAULT_MQTT_RETAIN true
#endif

#ifndef COOGLEIOT_DEFAULT_MQTT_QUEUE_SIZE
#define COOGLEIOT_DEFAULT_MQTT_QUEUE_SIZE 6
#endif

#ifndef COOGLEIOT_HEARTBEAT
#define COOGLEIOT_HEARTBEAT 30                  // 30 Seconds
#endif

#ifndef COOGLEIOT_FIRMWARE_UPDATE_CHECK
#define COOGLEIOT_FIRMWARE_UPDATE_CHECK 15 * 60 // 15 Minutes in Seconds
#endif

#ifndef COOGLEIOT_DNS_PORT
#define COOGLEIOT_DNS_PORT 53
#endif

#ifndef COOGLEIOT_EEPROM_SIZE
#define COOGLE_EEPROM_SIZE 1024
#endif

#ifndef COOGLEIOT_CFG_JSON_SIZE
#define COOGLE_CFG_JSON_SIZE 512
#endif

#ifndef COOGLEIOT_WEBSERVER_PORT
#define COOGLEIOT_WEBSERVER_PORT 80
#endif

#ifndef COOGLEIOT_MAX_WIFI_CONNECT_TIME
#define COOGLEIOT_MAX_WIFI_CONNECT_TIME 10
#endif

#ifndef COOGLEIOT_MAX_MQTT_ATTEMPTS
#define COOGLEIOT_MAX_MQTT_ATTEMPTS 10
#endif

#ifndef COOGLEIOT_DEVICE_TOPIC
#define COOGLEIOT_DEVICE_TOPIC "/coogleiot/devices"
#endif

#ifndef COOGLEIOT_DEBUG
#define COOGLEEEPROM_DEBUG
#endif

#ifndef COOGLEIOT_USE_MSGPACK
#define COOGLEEEPROM_USE_MSGPACK false
#endif

#endif
